### PR TITLE
Debugging playwright e2e tests

### PR DESCRIPTION
**Pull request by Bartvaderkin**
Trying to find out why random e2e tests are failing on locator timeouts.

I've seen it happen on webkit, chromium and firefox, and either the cookie_accept test or the multifile upload.

### CODE REVIEW

**Comment by Bartvaderkin** [comment]
Ugh no.. still `playwright._impl._errors.TimeoutError: Timeout 10000ms exceeded.` but this time in Firefox & the multifile upload

**Comment by Bartvaderkin** [comment]
I tried downgrading playwright to playwright==1.39.0 since we updated it to 1.41 for the Django update but same results.

**Comment by Bartvaderkin** [comment]
I think I smushed the cookie accept test as I haven't seen it in a while, but the multiple file upload test is still super flaky.

I added some waits and assertions but it even fails on the most basic visibility check.

**Comment by pi-sigma** [comment]
@Bartvaderkin Could we test the hypothesis (that we're running up against some infrastructure limit) by disabling most of the e2e tests and keep around the cookie-accept and the multiple-file-upload test (these are the ones I've seen failing myself)?

**Comment by Bartvaderkin** [comment]
@pi-sigma Seems reasonable, we can slap some `@skip` and see what happens.

**Comment by stevenbal** [comment]
I see these tests being flakey when I run the tests locally too, so I don't think it's an infrastructure thing?

**Comment by Bartvaderkin** [comment]
I don't know, I never had them fail locally and tried it a lot.

**Comment by Bartvaderkin** [comment]
Closing this as Steven is fixing it in his own branch and we don't need these extra timeouts etc right now.

**Pull request closed without merging**
