### PR TITLE
[#969] Feature/add django yubin

### PR DESCRIPTION
**Pull request by vaszig**

### CODE REVIEW

**Comment by vaszig** [comment]
The cronjobs for sending the emails are in another PR concerning deployment.

**Review by Bartvaderkin — CHANGES_REQUESTED** [review]
We should also add it to the admin-index fixture so we can view the messages in the admin.

**Comment by Bartvaderkin** [comment]
Ugh, I assumed we had a signal to reload admin-index fixture after a migrate, but we don't. 

I can't run `python src/manage.py loaddata django-admin-index` and can't see it used anywhere, maybe I misunderstood.

**Comment by vaszig** [comment]
Yes indeed..We have to run `python src/manage.py loaddata src/open_inwoner/conf/fixtures/django-admin-index.json` (realized that needs the complete path after some tries..)

**Review by alextreme — APPROVED** [review]

**Review by Bartvaderkin — APPROVED** [review]

**Pull request merged**
