### PR TITLE
:white_check_mark: - Add tests for compile_dependencies.

### PR DESCRIPTION
**Pull request by svenvandescheur**

### CODE REVIEW

**Comment by alextreme** [comment]
I'm neutral about this one, @annashamray and @vaszig what do you think?

**Comment by annashamray** [comment]
I don't mind but I think it should be run only if requirement of the `bin/compile_dependencies.sh` file is changed
We don't need it to run every time 
@svenvandescheur could you add `paths` to the gh action config?

**Comment by vaszig** [comment]
I am not very familiar with this kind of checking or optimizations but I agree with Anna concerning when we should run this.

**Review by annashamray — CHANGES_REQUESTED** [review]
Please limit the events which trigger the action

**Review by annashamray — CHANGES_REQUESTED** [review]

**Review by annashamray — APPROVED** [review]

**Pull request merged**
