### PR TITLE
:sparkles: [#1878] Post-login registration form for eHerkenning

### PR DESCRIPTION
**Pull request by stevenbal**
Based on https://github.com/maykinmedia/open-inwoner/pull/859, so that should be merged first

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1878

Aside from adapting the necessary registration form, the following was also changed/added:
- added eHerkenning link to registration page
- made DigiD/eHerkenning links on registration page conditional based on `settings.DIGID_ENABLED` and `SiteConfiguration.eherkenning_enabled`

### CODE REVIEW

**Comment by stevenbal** [comment]
I removed the first and last name fields from this form, I did notice however that the generated email is prefilled in the form:

image

I'm not sure if this is intentional, do we want this? @alextreme

**Comment by alextreme** [comment]
> I removed the first and last name fields from this form, I did notice however that the generated email is prefilled in the form:
> 
> image
> 
> I'm not sure if this is intentional, do we want this? @alextreme

How we deal with emailadresses and DigiD is a bit odd, but as it's a required field it is auto-generated. I'd recommend to do the same with eHerkenning, and if it's auto-generated that we hide this value just like with DigiD (it is overwritten anyway).

**Comment by stevenbal** [comment]
> and if it's auto-generated that we hide this value just like with DigiD (it is overwritten anyway).

Ah I see, I'll implement it the same for eHerkenning

**Review by alextreme — APPROVED** [review]
Looks good to me

**Pull request merged**
