### PR TITLE
[#2893] Remove search from mobile menu

### PR DESCRIPTION
**Pull request by pi-sigma**
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2893

### CODE REVIEW

**Comment by pi-sigma** [comment]
@jiromaykin should take a quick look as well when he's back

**Review by swrichards — APPROVED** [review]

**Comment by alextreme** [comment]
Fine if this works, however a neater approach would be to remove it from components/Header/Header.html. But considering the complexity of this template I agree with doing this via CSS for now

**Comment by jiromaykin** [comment]
@pi-sigma @alextreme  Oh dear.... This is not the way to do this.
Instead two blocks should have been removed from the Header HTML template, accounting for authenticated/non-authenticated:

```{% if cms_apps.products and request.user.is_authenticated or not config.hide_search_from_anonymous_users %}
 <li class="header__list-item">
  {% trans "Zoeken" as search %}
  {% link text=search href="/search" icon="search" icon_position="before" %}
 </li>
{% endif %}```


*** and also: ***


```{% elif config.login_show %}
        [ ... ]
       <li class="header__list-item">
        {% trans "Zoeken" as search %}
        {% link text=search href="/search" icon="search" icon_position="before" %}
       </li>```

**Comment by alextreme** [comment]
> @pi-sigma @alextreme Oh dear.... This is not the way to do this. Instead two blocks should have been removed from the Header HTML template, accounting for authenticated/non-authenticated:
> 
> ```
>  <li class="header__list-item">
>   {% trans "Zoeken" as search %}
>   {% link text=search href="/search" icon="search" icon_position="before" %}
>  </li>
> {% endif %}```
> 
> 
> *** and also: ***
> 
> 
> ```{% elif config.login_show %}
>         [ ... ]
>        <li class="header__list-item">
>         {% trans "Zoeken" as search %}
>         {% link text=search href="/search" icon="search" icon_position="before" %}
>        </li>```
> ```

feel free to create an issue/task and correct this

**Pull request merged**
