### PR TITLE
[#1645] improve design of product page

### PR DESCRIPTION
**Pull request by pi-sigma**
- make cta button text configurable
- remove mobile-view button from product detail template (unnecessary duplication)
- break up overflowing links in text field

Taiga: [#1645](https://taiga.maykinmedia.nl/project/open-inwoner/task/1645)

### CODE REVIEW

**Comment by alextreme** [comment]
A test that verifies that a modified button_text is shown on the product page would be appreciated. Might feel a bit simple though...

**Review by Bartvaderkin — COMMENTED** [review]
Code is decent but wouldn't it be nicer if this could've been edited through the placeholder? 

Like:
```
[CTABUTTON "click me!"]
```

**Comment by alextreme** [comment]
> Code is decent but wouldn't it be nicer if this could've been edited through the placeholder?
> 
> Like:
> 
> ```
> [CTABUTTON "click me!"]
> ```

Would indeed be more flexible, but I'd prefer to stick with Paul's simpler approach as making the markdown-content parsing more complicated may be tricky. I'm not sure if having multiple buttons with different names would be necessary, especially as all buttons point to the same URL/form...

**Review by Bartvaderkin — APPROVED** [review]

**Comment by alextreme** [comment]
Have made this PR ready-for-review, but allowing @pi-sigma to double-check just in case it was on Draft for a reason

**Comment by pi-sigma** [comment]
@alextreme Good to go, I forgot to mark it for review.

**Pull request merged**
