### PR TITLE
[#1963] Sort documents in case detail view

### PR DESCRIPTION
**Pull request by pi-sigma**
Taiga [#1963](https://taiga.maykinmedia.nl/project/open-inwoner/task/1963)

### CODE REVIEW

**Comment by pi-sigma** [comment]
@alextreme I encountered failing tests which were missing the `registratiedatum` attribute that I use to sort the document list. This makes me wonder about the assumptions we are making w.r.t. information objects.

The schema for `ZaakInformatieObject` does not require a `registratiedatum`, but our corresponding dataclass in `openzaak/api_models.py` assumes that the requirement is satisfied. Similarly, the file creation in our case detail view sets the `created` attribute on the file based on the `registratiedatum` of the `ZaakInformatieObject`. Can we assume that instances of `ZaakInformatieObject` have a `registratiedatum`. If not, how do we want to handle the sorting?

**Review by alextreme — CHANGES_REQUESTED** [review]
Consider fallback on title and ensure we have tests which show behaviour without registratiedatum

**Comment by pi-sigma** [comment]
@alextreme A creation date is indeed automatically inserted for documents without registratiedatum. Comparing them however is not straightforward because one is timezone-aware the other naive. I went with the solution you suggested, fallback on document title/name and unordered list, if necessary.

**Comment by alextreme** [comment]
@pi-sigma Good solution, however please add a regressiontest verifying the original issue that the newest document should be the first one, I didn't see this from your changes (but may have overlooked it)

**Review by alextreme — APPROVED** [review]

**Pull request merged**
