### PR TITLE
:sparkles: #391 - Allow description to be shown by a file.

### PR DESCRIPTION
**Pull request by svenvandescheur**
Schermafbeelding 2022-05-03 om 13 58 11

Can be populated by filling in the description field on the filer file.

### CODE REVIEW

**Comment by alextreme** [comment]
Taiga 445 is something Anna is working on and can be done separately
Taiga 481 is indeed picked up in PR #213 

@JostCrow and @annashamray please discuss this PR and if it needs further work. After the Actions Anna can continue with the Messages

**Comment by alextreme** [comment]
I noticed that a comment was already added when viewing the PR. Sven is on a holiday this week, this is the reason I've gotten involved.

**Comment by JostCrow** [comment]
Yes, but the comment is not clear enough. Because I did not know how it is now in the code that is is supposed to scroll down to the latest message in the conversation

**Comment by alextreme** [comment]
PR is for Jorik to approve/decline imho

**Review by alextreme — APPROVED** [review]

**Pull request merged**
