### PR TITLE
Issue#1016

### PR DESCRIPTION
**Pull request by svenvandescheur**

### CODE REVIEW

**Review by Bartvaderkin — CHANGES_REQUESTED** [review]
Cool, werkt nu stuk beter met toetsenbord.

Is het contrast van de focus-outline/border op die knoppen sterk genoeg?

**Comment by Bartvaderkin** [comment]
@svenvandescheur Something for the next time: can you please join the naming conventions of the project you're working on? 

For branch-name, git commit message and PR? Just 'issue-1016' doesn't mean much: if you look at the commit history you notice it becomes a bit chaotic and impossible to keep track.

`fix/<number>-something-recognizable` : eg: `fix/1016-search-feedback-accesibility` 

And for commit message/PR title:

"[#1016] Fixed search feedback accessibility."

Emoji's optional.

**Comment by svenvandescheur** [comment]
> Cool, works a lot better with keyboard.
> 
> Are we sure the contrast on the thumbs-buttons focus-outline/border is strong enough?

Didn't test, also not in scope of the ticket.

**Comment by svenvandescheur** [comment]
> @svenvandescheur I hope you did test the keyboard use because keyboard interaction was the first bullet in the ticket.

@Bartvaderkin yes

**Comment by svenvandescheur** [comment]
https://webaim.org/resources/contrastchecker/?fcolor=676767&bcolor=EDEDED

**Comment by svenvandescheur** [comment]
@Bartvaderkin contrast lijkt ok

**Review by Bartvaderkin — APPROVED** [review]

**Pull request merged**
